name: Cache CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/.cache
          key: cache-71db62d

      - name: prime-cache-71db62d
        run: |
          if [ "${{ steps.cache-step.outputs.cache-hit }}" = "true" ]; then
            echo "Cache hit"
          else
            echo "Cache miss"
          fi
